### ISSUE TITLE
Chosen plugin and Savvior

### ISSUE THREAD

**Issue by LoaiBassam** [attila/savvior#15]
Please have a look here: http://loai.directory/test/modules.php - do you see how Chosen dropdown menu's (http://harvesthq.github.io/chosen) are broken? 

I can fix them by simply calling <script type="text/javascript" src="assets/js/select-dropdowns.js"></script> before <script type="text/javascript" src="assets/js/grid-system.js"></script> but the problem with that is, you will then see the grid-system constructing its grids.

Please help.

**Comment by attila** [comment]
If this is an order of execution type of problem you could take advantage of events savvior emits -- i.e you could initialise chosen after savvior is ready or vice versa -- whichever works best.

**Comment by LoaiBassam** [comment]
I have tried the order of which the scripts are called by, tried all possible orders but to no avail. I got the chosen dropdown working fine using this method. By calling savvior after chosen. But the approach does not work with UI Juqury at all. 

What do you think I should do? 

Loai (Leo) Bassam

**Comment by attila** [comment]
The issue is within the asynchronous nature of savvior. When you call `savvior.init()` it sets up enquire handlers on media queries and the callbacks in those media query handlers are updating the DOM using `window.requestAnimationFrame()`. This means that you cannot expect that the next line of code will have the grid set up, it will happen later.

The most trivial solution for this would be the option to specify a callback in `savvior.init()` to make sure your other JS behaviours launch when the grid is ready. This is not supported at the moment, however you can set up an event listener to control the order of execution. Have a look at [this fiddle](https://jsfiddle.net/v9afct6p/)

Hope that helps.

**Comment by LoaiBassam** [comment]
Thank you, I have tried what you have suggested, it did not work as expceted, it keep on showing errors like "too much recursion" in Firefox, it keep on creating dropdowns and act weirdly... Do you think a solution might be to run .grid when everything has loaded? or before anything is loaded? so they won't conflict?

**Comment by attila** [comment]
Still the same problem, when datepicker is initialised, savvior is in the middle of creating the grid and the input field to attach datepicker on is not in the DOM at that moment. Unless you initialise your behaviours in event listeners, you will run into problems like this.

**Comment by LoaiBassam** [comment]
I have did like you told me, but it breaks the page, please have a look here: http://loai.directory/test/test/modules.php and here http://loai.directory/test/test

**Comment by attila** [comment]
I tested http://loai.directory/test/test on Firefox and on Chrome and did not see JS related errors in the console. There is a FOUC on the page but that you can mitigate by optimising for performance and adjusting your CSS.

It is also worth noting that the event "savvior:redraw" is fired every time a grid element is redrawn. The element being redrawn is passed in the original event as `event.detail.element`. It is useful to have additional checks to make sure you only execute code the number of times needed and exactly when it is needed.

**Comment by LoaiBassam** [comment]
Attila, I honestly have no idea what you are telling me to do. I don't really know JavaScript and Jquery that is why I am using your plug-in. 

If I gave this URL to a JQuery developer, would they know what to do? 

Thank you so much for your help, but I really don't know what I am doing, sorry for bombarding you with questions all the time.

**Comment by LoaiBassam** [comment]
Oh, I seem to got it working now, but it just does not work on Firefox! Am I missing something?

**Comment by LoaiBassam** [comment]
I gave up - I will just add the UI elements inside manual grids for now, but can you please tell me when would you be able to update the plugin with this feature?

**Comment by attila** [comment]
It seems to work just fine on Firefox. I am sorry I could not help you with your support requests. I have limited time to work on savvior right now but will surely think about adding a callback in the future.

**Comment by LoaiBassam** [comment]
You have done a great job doing that plugin together mate. You have helped greatly already, thank you! I will just need to wait for the new version.

Thank you ever so much and I really hope I can put my hands on the updated version very soon.
