### ISSUE TITLE
Savvior.destroy causing exception on enquire js

### ISSUE THREAD

**Issue by ev5unleash** [attila/savvior#21]
Hi there,

So far, I'm loving the minimalistic nature of savvior! I do have on issue with it however... I'm dynamically loading in div's that I wish to attach savvior to. After I load in the div I use the code:

savvior.init('#cards', {
            "screen and (max-width: 20em)": { columns: 2 },
            "screen and (min-width: 20em) and (max-width: 40em)": { columns: 2 },
            "screen and (min-width: 40em)": { columns: 2 },
        });

When I'm about to unload this content I call, "savvior.destroy();". However, when I call this function, an exception from enquire comes up saying "TypeError: this.msql.removeListener is not a function.". I double checked my work to make sure I wasn't destroying the actual div I've attached Savvior to and still getting the same thing. 

EDIT: It seems to have to do with the function unregister in Enquire. Full error: TypeError: this.mql.removeListener is not a function at Object.f.clear (enquire.min.js:7:1559) at Object.g.unregister (enquire.min.js:7:1998) at savvior.min.js:6:5278 at c (savvior.min.js:6:365) at g.unregister (savvior.min.js:6:5243) at null.<anonymous> (savvior.min.js:6:6252) at c (savvior.min.js:6:365) at h.destroy (savvior.min.js:6:6207) at HTMLDivElement.<anonymous> (page.js:33:21) at HTMLDivElement.d (https://code.jquery.com/jquery-2.1.1.min.js:3:10897)

Any ideas? I'm going to post this on Enquire's hub too.

Thanks,

**Comment by attila** [comment]
Thanks for reporting a bug. Could you set up a jsfiddle or codepen so I can track it down?

Also, I wonder why you set up 3 different media queries when the grid should have the same amount of columns at every media query match? Why not
```
savvior.init('#cards', {
  'screen': { columns: 2 }
});
```

**Comment by ev5unleash** [comment]
Hi there Attila,

To be honest, I was just using the default configuration on the website. Using the basic 2 columns init seemed to fix my issue! Thank you!

**Comment by attila** [comment]
Glad that it worked out in the end. Feel free to report back if you find more issues.

**Comment by lpwz** [comment]
You could Fix enquire.js

https://github.com/WickyNilliams/enquire.js/issues/124

--------------------------------------------------------------------
intrasoft-eu commented on 25 Feb 2015
The same for me on Chrome 40. It's connected with this part:

this.listener = function(mql) {
  self.mql = mql;
  self.assess();
};
My quick fix:

this.listener = function(mql) {
  if (mql.currentTarget) {
    self.mql = mql.currentTarget;
  } else {
    self.mql = mql;
  }
  self.assess();
};
