### ISSUE TITLE
Evenly space items in grid?

### ISSUE THREAD

**Issue by emzero** [attila/savvior#24]
I'm not being able to distribute items evenly across the grid. What I mean is, how to make it so both the vertical and horizontal margin between items is the same.

In this codepen (http://codepen.io/emzero/pen/eZzPQj) you can see the horizontal margin depends on the width of the window. I'd like items to have a specific margin between them and center the whole grid in its container if necessary.

**Comment by attila** [comment]
I'm not sure what you mean but having an equal margin between columns and items is a simple CSS related question, see http://codepen.io/anon/pen/PNGJeP

**Comment by emzero** [comment]
I want the images to have a 10px margin between them. In your example the .item divs are bigger than the images, so they fill up the empty space.
In my codepen, if you maximize the browser window, you end up having a lot of horizontal space between the images. I want to set that space to a fixed size, say 10px, just like vertical margin.
