### ISSUE TITLE
Does it support appending/prepending items as well as removing them?

### ISSUE THREAD

**Issue by emzero** [attila/savvior#25]
Sorry I haven't had the time to try it yet, but I wanted to ask if this library supports dynamically adding/removing items from the grid while redrawing the grid properly.

**UPDATE**
I have made this [simple codepen ](http://codepen.io/emzero/pen/eZzPQj)and it doesn't work as expected. Any way of make it work? Is there any `savvior.redraw()` method or something?

**Comment by attila** [comment]
Append/prepend has been added in https://github.com/attila/savvior/pull/23.
No new releases were pushed since then so you will need to grab from the master branch to use it right away.
