### ISSUE TITLE
When is savvior done ?

### ISSUE THREAD

**Issue by wirmachenbunt** [attila/savvior#27]
is there a way to figure out when savvior is finished so i can trigger some js library after savvior ?

**Comment by attila** [comment]
In the current version an event called `savvior:setup` is dispatched on `window`. The event object contains more information on the grid being set up, i.e:
```js
window.addEventListener('savvior:setup', function(e) {
  console.log(e.detail); // Outputs: { element: [Element], columns: [Number], filter: [Grid.filter] }
});
```

Hope that helps.

**Comment by wirmachenbunt** [comment]
hey cheers for the quick answer
