### ISSUE TITLE
IE8 - Object doesn't support property or method 'createEvent'

### ISSUE THREAD

**Issue by claudchan** [attila/savvior#29]
Hi,
An issue on IE8 Object doesn't support property or method 'createEvent'
Possible to make support on this?

**Comment by attila** [comment]
IE8 is not supported. Is it possible to polyfill the behaviour?

**Comment by claudchan** [comment]
I unable to find the polyfill for 'createEvent'.
But I notice that, there are other plugin developer also coded with 'createEvent' and there are no issue running on IE8. Example of Bootstrap select: http://silviomoreto.github.io/bootstrap-select
Maybe you need to change a bit on your scripts that will work around.

**Comment by attila** [comment]
Not supporting IE8 was a conscious choice as it does not even have support for media queries let alone matchMedia. This isn't something I plan to add I'm afraid.
