### ISSUE TITLE
Infinite scroll layout

### ISSUE THREAD

**Issue by starise** [attila/savvior#3]
First thanks for this awesome stuff.
I want to achieve an infinite scroll layout using savvior. There're some "append/prepend" methods like in Masonry or Salvattore?

**Comment by attila** [comment]
Thanks for opening this.
Having append/prepend methods has always been planned although these aren't implemented yet. Do you fancy sending in a PR? :)

**Comment by jfeust** [comment]
+1 on this.

**Comment by e1himself** [comment]
+1

**Comment by attila** [comment]
Did some work on this, now there is a PR open (https://github.com/attila/savvior/pull/23). Please check out that branch and feed back on that PR with any of your findings.
