### ISSUE TITLE
Loading savvior with Webpack, es6 modules / CommonJS

### ISSUE THREAD

**Issue by owenhoskins** [attila/savvior#32]
Hello. I am eager to try out your masonry system in a current project with static-site generator https://gitter.im/MoOx/phenomic but when building it throws this error:

```
✖ Error in ./~/savvior/dist/savvior.js
Module not found: Error: Cannot resolve module 'enquire' in ./node_modules/savvior/dist
 @ ./~/savvior/dist/savvior.js 4:4-6:6
```

I've confirmed that `enquire.js` is in it's proper place in `node_modules` within `node_modules/savvior`

Not sure what the issue could be perhaps since the project is using Webpack instead of Browserfiy?

Any suggestions would be greatly appreciated, thanks!

**Comment by attila** [comment]
Interesting that I haven't tried to include this in a Webpack-based project yet. It could be that the umd wrapper declares the dependency as `enquire` and not `enquire.js` for amd and webpack never actually reaches the CommonJS branch of the umd wrapper where `enquire.js` is required.

This module structure badly needs a modernisation but for now the easiest would probably be to [set an alias](https://webpack.github.io/docs/configuration.html#resolve-alias) in webpack to point to a valid location.

**Comment by Luddinus** [comment]
same issue here
