### ISSUE TITLE
Wrong column count if resizing from big to small width

### ISSUE THREAD

**Issue by vlad00777** [attila/savvior#33]
Hi. I creating demo on codepen: http://codepen.io/anon/pen/ZKELEj
You can seen this bug if resizing window.

**Comment by attila** [comment]
Hi there, thanks for trying out savvior! I confirm this is not a bug. You will need to define your media queries more explicit as this won't cascade like CSS. Try:
```es6
savvior.init(".insideBlock_newsList", {
  'screen and (min-width: 1201px)': { columns: 3 },
  'screen and (min-width: 800px) and (max-width: 1200px)': { columns: 2 },
  'screen and (max-width: 798px)': { columns: 1 }
});
```
