### ISSUE TITLE
I can't get it working

### ISSUE THREAD

**Issue by LoaiBassam** [attila/savvior#4]
How can I get this working? it is not JavaScript?

**Comment by attila** [comment]
It is written in JavaScript :) Details of usage can be found in the [readme](/attila/savvior/blob/master/README.md).

Could you be a bit more specific? Do you have a link to look at perhaps?

**Comment by LoaiBassam** [comment]
Thank you so much for your quick response!

So I have downloaded enquire.js and savvior.js from (https://github.com/attila/savvior/blob/master/dist/savvior.js), then I added the following to the CSS:
    
/*GRID SYSTEM //////*/
.column { float: left; }
.size-1of2 { width: 50%; }
.size-1of3 { width: 33.33333%; }
.size-1of4 { width: 25%; }

and then in the index.php I added

<div id="myGrid">
  <div class="box"><span></span></div>
  <div class="box"><span></span></div>
  <div class="box"><span></span></div>
  <div class="box"><span></span></div>
  <div class="box"><span></span></div>
  <div class="box"><span></span></div>
  <div class="box"><span></span></div>
  <div class="box"><span></span></div>
  <div class="box"><span></span></div>
  <div class="box"><span></span></div>
  <div class="box"><span></span></div>
</div>

and at the very end just before closing tags I added: 

        <script type="text/javascript">
var mq = Modernizr.mq("only all");
Modernizr.load([{
  test: mq && !window.matchMedia, // Media query support wihtout matchMedia support.
  yep: "/path/to/media.match.js", // Load the polyfill for matchMedia
  complete: function() {
    (typeof window.matchMedia === "function") && Modernizr.load('assets/includes/js/main.js');
  }
},
{
  load: 'assets/js/grid-system.js',
  complete: function() {
      // Initialise savvior here.
    }
  }
}]);
</script>
<script>
savvior.init("#myGrid", {
    "screen and (max-width: 20em)": { columns: 2 },
    "screen and (min-width: 20em) and (max-width: 40em)": { columns: 3 },
    "screen and (min-width: 40em)": { columns: 4 },
  });
</script>

but it just does not work, am I doing it right?
Thank you again 
leo


Leo Bassam 
Find me on:  Facebook | Twitter | Google+ | Linkedin | Dribbble | Behance

**Comment by LoaiBassam** [comment]
I have got it working, I did not link the paths inside the <scripts> correctly. However, I have left: yep: "/path/to/media.match.js", // Load the polyfill for matchMedia as it is, is that okay?

**Comment by attila** [comment]
Just a safety question, did you load modernizr.js at all via a `<script>` tag or by other means?
I do not see where enquire.js or savvior.js is loaded in the provided code sample.
Also make sure you initialise savvior in its `complete` callback -- right where the code comment says `// Initialise savvior here.` as Modernizr loads the script asynchronously.

**Comment by attila** [comment]
The polyfill for matchMedia is only needed if you plan to support browsers with media query support but without matchMedia support (e.g IE9)

**Comment by LoaiBassam** [comment]
Thank you again, I have one more problem. I gave the parent a class .hide which is basically: display: none - when I looked at the HTML, the plugin did not create any of the columns, so when I display it at a later stage there is no columns present. Please take a look at the question I posted here: http://stackoverflow.com/questions/28659488/grid-system-does-not-work-when-it-is-inside-a-hidden-div it might explain the problem more clearer. Thank you again!

**Comment by attila** [comment]
Why don't you initialise the plugin in the callback where you show the div then?
Alternatively you could use `visibility: hidden` perhaps?

**Comment by LoaiBassam** [comment]
visibility: hidden would work, but I can't use it. The reason why I am trying to get it to work even if the container is displayed: none; is becouse I want to be able to use the grid system to layout forms and page structures, it will be used in the UI tabs and inside popups where the container is displayed none by default until it is called

**Comment by attila** [comment]
Thanks for raising this. Constructing grids in a hidden container is [not](https://github.com/attila/savvior/blob/master/src/Grid.js#L26) [supported](https://github.com/attila/savvior/blob/master/src/GridHandler.js#L33) at the moment, Although I do not remember why these tests are in place as there should be no problem of acting on a hidden container. I will look into this. Follow #5 for updates, thanks!
