### ISSUE TITLE
Add support for hidden containers

### ISSUE THREAD

**Issue by attila** [attila/savvior#5]
There should be no problem of setting up the grid container if the element is hidden via CSS.

**Comment by LoaiBassam** [comment]
Thank you ever so much! Would you like me to provide a live test site?

**Comment by attila** [comment]
Looked at it in more detail and realised that this limitaion should be abolished as there is no real difference in the way the grids are constructed if the container happens to be hidden in CSS.

So this limitation is now removed and the test suite is extended to act on hidden containers now. Please use release v0.4.2 or grab the latest from the master

**Comment by LoaiBassam** [comment]
It worked like a charm! Thank you ever so much for all of your time and effort in creating this marvelous plugin!
