### ISSUE TITLE
Can't Initialize savvior 

### ISSUE THREAD

**Issue by LoaiBassam** [attila/savvior#6]
I can't seem to be able to get it working when I add the initialize code where it says // Initialize savvior here.

I copied the snippet below without the <script>

	savvior.init(".grid", {
		"screen and (max-width: 500px)": { columns: 1 },
		"screen and (min-width: 500px) and (max-width: 1024px)": { columns: 1 },
		"screen and (min-width: 1024px) and (max-width: 2000px)": { columns: 1 },
		"screen and (min-width: 2000px)": { columns: 1 },
	});
	
	savvior.init(".grid.columns2", {
		"screen and (max-width: 500px)": { columns: 1 },
		"screen and (min-width: 500px) and (max-width: 1024px)": { columns: 2 },
		"screen and (min-width: 1024px) and (max-width: 2000px)": { columns: 2 },
		"screen and (min-width: 2000px)": { columns: 3 },
	});
	
	savvior.init(".grid.columns3", {
		"screen and (max-width: 500px)": { columns: 1 },
		"screen and (min-width: 500px) and (max-width: 1024px)": { columns: 2 },
		"screen and (min-width: 1024px) and (max-width: 2000px)": { columns: 3 },
		"screen and (min-width: 2000px)": { columns: 4 },
	});
	
	savvior.init(".grid.columns4", {
		"screen and (max-width: 500px)": { columns: 1 },
		"screen and (min-width: 500px) and (max-width: 1024px)": { columns: 2 },
		"screen and (min-width: 1024px) and (max-width: 2000px)": { columns: 4 },
		"screen and (min-width: 2000px)": { columns: 5 },
	});

and pasted it where it says // Initialise savvior here.

var mq = Modernizr.mq("only all");
Modernizr.load([{
  test: mq && !window.matchMedia, // Media query support wihtout matchMedia support.
  yep: "assets/js/grid-system.js", // Load the polyfill for matchMedia
  complete: function() {
    (typeof window.matchMedia === "function") && Modernizr.load('assets/js/grid-system.js');
  }
},
{
  load: 'assets/js/grid-system.js',
  complete: function() {
      // Initialise savvior here.
    }
  }
}]);

But it does not work, what am I doing wrong?

**Comment by attila** [comment]
Please refer to the examples at https://github.com/attila/savvior-examples, hope that helps, thank you.

**Comment by LoaiBassam** [comment]
I have followed the examples already, but it won't get initialized with me, please can you review the script below? 

var mq = Modernizr.mq("only all");
Modernizr.load([{
  test: mq && !window.matchMedia, // Media query support wihtout matchMedia support.
  yep: "assets/js/grid-system.js", // Load the polyfill for matchMedia
  complete: function() {
    (typeof window.matchMedia === "function") && Modernizr.load('assets/js/grid-system.js');
  }
},
{
  load: 'assets/js/grid-system.js',
  complete: function() {
      	savvior.init(".grid", {
		"screen and (max-width: 500px)": { columns: 1 },
		"screen and (min-width: 500px) and (max-width: 1024px)": { columns: 1 },
		"screen and (min-width: 1024px) and (max-width: 2000px)": { columns: 1 },
		"screen and (min-width: 2000px)": { columns: 1 },
	});
	
	savvior.init(".grid.columns2", {
		"screen and (max-width: 500px)": { columns: 1 },
		"screen and (min-width: 500px) and (max-width: 1024px)": { columns: 2 },
		"screen and (min-width: 1024px) and (max-width: 2000px)": { columns: 2 },
		"screen and (min-width: 2000px)": { columns: 3 },
	});
	
	savvior.init(".grid.columns3", {
		"screen and (max-width: 500px)": { columns: 1 },
		"screen and (min-width: 500px) and (max-width: 1024px)": { columns: 2 },
		"screen and (min-width: 1024px) and (max-width: 2000px)": { columns: 3 },
		"screen and (min-width: 2000px)": { columns: 4 },
	});
	
	savvior.init(".grid.columns4", {
		"screen and (max-width: 500px)": { columns: 1 },
		"screen and (min-width: 500px) and (max-width: 1024px)": { columns: 2 },
		"screen and (min-width: 1024px) and (max-width: 2000px)": { columns: 4 },
		"screen and (min-width: 2000px)": { columns: 5 },
	});
    }
  }
}]);

**Comment by attila** [comment]
I really mean it, I just added the repo savvior-examples where [examples-modernizr.html](https://github.com/attila/savvior-examples/blob/master/html/example_modernizr.html#L58) contains a Modernizr-based implementation.

Reading your code it is unclear what is contained in "assets/js/grid-system.js" and why it is loaded twice in your code.

**Comment by LoaiBassam** [comment]
Sorry for being pain Attila, I am really unfamiliar with this, will just ask the question on Hackhands - I am missing something but can't figure out what. Thank you every so much for your help and GREAT plugin :)
