### ISSUE TITLE
Problem with having multi grids on the same page

### ISSUE THREAD

**Issue by LoaiBassam** [attila/savvior#8]
When you have two or more .grids with the same settings, only the first one works and the rest does not. 

For example: 

<div class="grid columns3">
</div>
<div class="grid columns3">
</div>
<div class="grid columns4">
</div>

Only the first .columns 3 will work and columns 4 but not the middle one. Please help

**Comment by attila** [comment]
Savvior internals use document.querySelector() to select the container element so I suggest you use IDs for multiple containers.

**Comment by LoaiBassam** [comment]
Can we tweak it to use .each? Changing to IDs will require me to re-build everything which I have done around the grids. Please is there a more quicker approach by tweaking the js?

Loai (Leo) Bassam

**Comment by attila** [comment]
Thought about this feature request and started working on it. A very basic version of this is pushed to a branch named multiple_grids in commit fcce81abdf76986c8928970b68bc087e1ad1410e.

Can you please test this in your setup? You'll need to check out that branch and build files to dist yourself. For this have grunt installed and run `npm install && grunt` then use savvior.js from `dist/` in your project.

**Comment by LoaiBassam** [comment]
Sorry Attila, I did not get it working. Would you include it in the main.js?

**Comment by attila** [comment]
No worries I ran the build so you can try it out. Download https://github.com/attila/savvior/archive/multiple_grids.zip and look for the dist folder for updated versions.

**Comment by LoaiBassam** [comment]
Thank you for your prompt response Attila. I have replaced the old version with the new code you have under dist, but none of the grids works now :/ - do you think I am missing something?

**Comment by attila** [comment]
Can you set this on jsfiddle or somewhere similar so everything is visible in your setup, including JS code please?

**Comment by LoaiBassam** [comment]
I have uploaded the site to http://loai.directory/test 

Thank you :)

**Comment by attila** [comment]
I see lots of assets not loading on the page. Could you set up an isolated jsfiddle or codepen instead? It may help you with debugging the situation.

**Comment by LoaiBassam** [comment]
Please have a look now, I have removed everything else: http://loai.directory/test/

**Comment by attila** [comment]
Still broken with a lot of 404s, have a look please.
![404](https://cloud.githubusercontent.com/assets/236630/7184066/16f603d6-e453-11e4-8a87-579865d617b2.png)

**Comment by LoaiBassam** [comment]
Oh! I know why - fixed: http://loai.directory/test/

**Comment by attila** [comment]
I see the problem now. You are calling several savvior instances but the selectors are overlapping:
```js
      savvior.init(".grid", {
		"screen and (max-width: 500px)": { columns: 1 },
		"screen and (min-width: 500px) and (max-width: 1024px)": { columns: 1 },
		"screen and (min-width: 1024px) and (max-width: 2000px)": { columns: 1 },
		"screen and (min-width: 2000px)": { columns: 1 },
	});
	
	savvior.init(".grid.columns2", {
		"screen and (max-width: 500px)": { columns: 1 },
		"screen and (min-width: 500px) and (max-width: 1024px)": { columns: 2 },
		"screen and (min-width: 1024px) and (max-width: 2000px)": { columns: 2 },
		"screen and (min-width: 2000px)": { columns: 3 },
	});
	
	savvior.init(".grid.columns3", {
    	"screen and (max-width: 500px)": { columns: 1 },
		"screen and (min-width: 500px) and (max-width: 1024px)": { columns: 2 },
		"screen and (min-width: 1024px) and (max-width: 2000px)": { columns: 3 },
		"screen and (min-width: 2000px)": { columns: 4 },
	});
	
	savvior.init(".grid.columns4", {
		"screen and (max-width: 500px)": { columns: 1 },
		"screen and (min-width: 500px) and (max-width: 1024px)": { columns: 2 },
		"screen and (min-width: 1024px) and (max-width: 2000px)": { columns: 4 },
		"screen and (min-width: 2000px)": { columns: 5 },
	});
	
	savvior.init(".grid.columns5", {
		"screen and (max-width: 500px)": { columns: 1 },
		"screen and (min-width: 500px) and (max-width: 1024px)": { columns: 2 },
		"screen and (min-width: 1024px) and (max-width: 2000px)": { columns: 5 },
		"screen and (min-width: 2000px)": { columns: 5 },
	});
```
Assuming you want a single grid behaviour attached to a container at a time, I suggest using separate class names for separate desired grid configurations. Here `.grid` applies to all your containers and it's certainly causing a problem as multiple grid configurations are applied to a single container.

Hope that makes sense.

**Comment by LoaiBassam** [comment]
Thank you very much! That fixed the problem :)

**Comment by attila** [comment]
On another note I think it's very important to have some mechanism to prevent these situations. The plugin should fail silently and exclude a container if it's already part of another configuration.

**Comment by LoaiBassam** [comment]
Sorry didn't get you :/

**Comment by attila** [comment]
I mean on a setup you showed savvior should simply skip processing the container found with `.columns2` if it's already processed under `.grid`

**Comment by LoaiBassam** [comment]
I changed the classes completely, is that what you mean?

![capture](https://cloud.githubusercontent.com/assets/4785390/7184667/6c85b924-e456-11e4-980a-6dd5d010558a.JPG)

**Comment by attila** [comment]
Your setup is fine as is now. :+1: 
I will need to improve savvior to be smarter when someone does not set it up correctly.

**Comment by LoaiBassam** [comment]
Thanks :) I must thank you again for creating this plugin, it is absolutely brilliant!
